services:

  api:
    build:
      context: .
      dockerfile: dockerfiles/api.Dockerfile
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
      - APP_URL=${REACT_APP_APP_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MAX_NB_TOOLS=${MAX_NB_TOOLS}
    depends_on:
      - db
    volumes:
      - ./api:/app/api

  app:
    build:
      context: .
      dockerfile: dockerfiles/app.Dockerfile
    ports:
      - "3000:3000"
    command: npm start
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
      - REACT_APP_MAX_NB_TOOLS=${MAX_NB_TOOLS}
    depends_on:
      - api
    volumes:
      - ./app:/app
      - /app/node_modules

  db:
    image: postgres:13
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

# volumes:
#   postgres_data:
